site_name: Hardening Guide for Homelabs
site_url: https://xfuture603.github.io/homelab-hardening-guide/
repo_url: https://github.com/xFuture603/homelab-hardening-guide
repo_name: Homelab Hardening Guide
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - document-dates:
      position: bottom
      type: date
      date_format: '%Y-%m-%d'
      time_format: '%H:%M:%S'
      show_author: text
nav:
  - Overview: index.md
  - Networking:
    - network/index.md
  - Operating System:
    - os/index.md
    - Package Managers:
      - os/package-managers/gpg-keys.md
    - SSH:
      - os/ssh/index.md
      - os/ssh/non-standard-port.md
      - os/ssh/ssh-keys.md
      - os/ssh/disable-root-login.md
      - os/ssh/remove-outdated-protocols.md
      - os/ssh/limit-logins-to-user-or-ip.md
      - os/ssh/two-factor-authentication.md
  - Containerization:
    - containerization/index.md
    - Docker:
      - containerization/docker/index.md
      - containerization/docker/docker-in-rootless-mode.md
      - containerization/docker/docker-socket-proxy.md
      - containerization/docker/prevent-privilege-escalation.md
      - containerization/docker/restrict-privileges-and-capabilities.md
      - containerization/docker/set-resource-limits.md
  - Web Security:
    - web-security/index.md
    - web-security/hsts.md
    - web-security/http-headers.md
  - Tooling:
    - tooling/index.md
    - IPS:
      - tooling/intrusion-prevention-systems/fail2ban.md
    - tooling/quick-wins.md
theme:
  name: material
  font:
    text: Work Sans
  features:
    - navigation.indexes
#  favicon: assets/favicon.ico
#  logo: assets/tbd.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode view
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode view
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
